apiVersion: v1
kind: Service
metadata:
  name: nginx-service-recreate
spec:
  type: NodePort
  selector:
    app: nginx
    update: recreate
  ports:
    - protocol: http
      port: 80
      targetPort: 80