apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxoss-deployment
  labels:
    app: nginxoss
spec:
  replicas: 3
  strategy:
    type: Recreate
  minReadySeconds: 20   # 파드가 Ready 상태로 유지될 최소 시간 (예: 20초)
  selector:
    matchLabels:
      app: nginxoss
  template:
    metadata:
      labels:
        app: nginxoss
    spec:
      containers:
      - name: nginxoss-container
        image: nginx
        ports:
        - containerPort: 80
