apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-rollout
  labels:
    app: nginx
    update: rollout
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
      update: rollout
  template:
    metadata:
      labels:
        app: nginx
        update: rollout
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80