apiVersion: v1
kind: Service
metadata:
  name: nginx-service-rollout
spec:
  type: NodePort
  selector:
    app: nginx
    update: rollout
  ports:
    - protocol: http
      port: 80
      targetPort: 80